# The Okta software accompanied by this notice is provided pursuant to the following terms:
# Copyright © 2025-Present, Okta, Inc.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
# License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
# coding: utf-8

"""
Okta Admin Management

Allows customers to easily access the Okta Management APIs

The version of the OpenAPI document: 5.1.0
Contact: devex-public@okta.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from okta.models.href_object import HrefObject
from okta.models.href_object_activate_link import HrefObjectActivateLink
from okta.models.href_object_deactivate_link import HrefObjectDeactivateLink
from okta.models.href_object_self_link import HrefObjectSelfLink


class ApplicationLinks(BaseModel):
    """
    ApplicationLinks
    """  # noqa: E501

    access_policy: Optional[HrefObject] = Field(default=None, alias="accessPolicy")
    activate: Optional[HrefObjectActivateLink] = None
    deactivate: Optional[HrefObjectDeactivateLink] = None
    groups: Optional[HrefObject] = None
    logo: Optional[List[HrefObject]] = None
    metadata: Optional[HrefObject] = None
    var_self: Optional[HrefObjectSelfLink] = Field(default=None, alias="self")
    users: Optional[HrefObject] = None
    __properties: ClassVar[List[str]] = [
        "accessPolicy",
        "activate",
        "deactivate",
        "groups",
        "logo",
        "metadata",
        "self",
        "users",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplicationLinks from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of access_policy
        if self.access_policy:
            if not isinstance(self.access_policy, dict):
                _dict["accessPolicy"] = self.access_policy.to_dict()
            else:
                _dict["accessPolicy"] = self.access_policy

        # override the default output from pydantic by calling `to_dict()` of activate
        if self.activate:
            if not isinstance(self.activate, dict):
                _dict["activate"] = self.activate.to_dict()
            else:
                _dict["activate"] = self.activate

        # override the default output from pydantic by calling `to_dict()` of deactivate
        if self.deactivate:
            if not isinstance(self.deactivate, dict):
                _dict["deactivate"] = self.deactivate.to_dict()
            else:
                _dict["deactivate"] = self.deactivate

        # override the default output from pydantic by calling `to_dict()` of groups
        if self.groups:
            if not isinstance(self.groups, dict):
                _dict["groups"] = self.groups.to_dict()
            else:
                _dict["groups"] = self.groups

        # override the default output from pydantic by calling `to_dict()` of each item in logo (list)
        _items = []
        if self.logo:
            for _item in self.logo:
                if _item:
                    _items.append(_item.to_dict())
            _dict["logo"] = _items
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            if not isinstance(self.metadata, dict):
                _dict["metadata"] = self.metadata.to_dict()
            else:
                _dict["metadata"] = self.metadata

        # override the default output from pydantic by calling `to_dict()` of var_self
        if self.var_self:
            if not isinstance(self.var_self, dict):
                _dict["self"] = self.var_self.to_dict()
            else:
                _dict["self"] = self.var_self

        # override the default output from pydantic by calling `to_dict()` of users
        if self.users:
            if not isinstance(self.users, dict):
                _dict["users"] = self.users.to_dict()
            else:
                _dict["users"] = self.users

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplicationLinks from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "accessPolicy": (
                    HrefObject.from_dict(obj["accessPolicy"])
                    if obj.get("accessPolicy") is not None
                    else None
                ),
                "activate": (
                    HrefObjectActivateLink.from_dict(obj["activate"])
                    if obj.get("activate") is not None
                    else None
                ),
                "deactivate": (
                    HrefObjectDeactivateLink.from_dict(obj["deactivate"])
                    if obj.get("deactivate") is not None
                    else None
                ),
                "groups": (
                    HrefObject.from_dict(obj["groups"])
                    if obj.get("groups") is not None
                    else None
                ),
                "logo": (
                    [HrefObject.from_dict(_item) for _item in obj["logo"]]
                    if obj.get("logo") is not None
                    else None
                ),
                "metadata": (
                    HrefObject.from_dict(obj["metadata"])
                    if obj.get("metadata") is not None
                    else None
                ),
                "self": (
                    HrefObjectSelfLink.from_dict(obj["self"])
                    if obj.get("self") is not None
                    else None
                ),
                "users": (
                    HrefObject.from_dict(obj["users"])
                    if obj.get("users") is not None
                    else None
                ),
            }
        )
        return _obj
