# The Okta software accompanied by this notice is provided pursuant to the following terms:
# Copyright © 2025-Present, Okta, Inc.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
# License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
# coding: utf-8

"""
Okta Admin Management

Allows customers to easily access the Okta Management APIs

The version of the OpenAPI document: 5.1.0
Contact: devex-public@okta.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set

from pydantic import ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Annotated
from typing_extensions import Self

from okta.models.authenticator_method_with_verifiable_properties import (
    AuthenticatorMethodWithVerifiableProperties,
)
from okta.models.links_self_and_lifecycle import LinksSelfAndLifecycle
from okta.models.otp_protocol import OtpProtocol
from okta.models.otp_totp_algorithm import OtpTotpAlgorithm
from okta.models.otp_totp_encoding import OtpTotpEncoding


class AuthenticatorMethodOtp(AuthenticatorMethodWithVerifiableProperties):
    """
    AuthenticatorMethodOtp
    """  # noqa: E501

    acceptable_adjacent_intervals: Optional[
        Annotated[int, Field(le=10, strict=True, ge=0)]
    ] = Field(default=None, alias="acceptableAdjacentIntervals")
    algorithm: Optional[OtpTotpAlgorithm] = None
    encoding: Optional[OtpTotpEncoding] = None
    factor_profile_id: Optional[StrictStr] = Field(
        default=None, alias="factorProfileId"
    )
    pass_code_length: Optional[
        Annotated[int, Field(multiple_of=2, le=10, strict=True, ge=6)]
    ] = Field(default=None, alias="passCodeLength")
    protocol: Optional[OtpProtocol] = None
    time_interval_in_seconds: Optional[StrictInt] = Field(
        default=None, alias="timeIntervalInSeconds"
    )
    __properties: ClassVar[List[str]] = [
        "status",
        "type",
        "_links",
        "verifiableProperties",
        "acceptableAdjacentIntervals",
        "algorithm",
        "encoding",
        "factorProfileId",
        "passCodeLength",
        "protocol",
        "timeIntervalInSeconds",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthenticatorMethodOtp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            if not isinstance(self.links, dict):
                _dict["_links"] = self.links.to_dict()
            else:
                _dict["_links"] = self.links

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthenticatorMethodOtp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "status": obj.get("status"),
                "type": obj.get("type"),
                "_links": (
                    LinksSelfAndLifecycle.from_dict(obj["_links"])
                    if obj.get("_links") is not None
                    else None
                ),
                "verifiableProperties": obj.get("verifiableProperties"),
                "acceptableAdjacentIntervals": obj.get("acceptableAdjacentIntervals"),
                "algorithm": obj.get("algorithm"),
                "encoding": obj.get("encoding"),
                "factorProfileId": obj.get("factorProfileId"),
                "passCodeLength": obj.get("passCodeLength"),
                "protocol": obj.get("protocol"),
                "timeIntervalInSeconds": obj.get("timeIntervalInSeconds"),
            }
        )
        return _obj
