# The Okta software accompanied by this notice is provided pursuant to the following terms:
# Copyright © 2025-Present, Okta, Inc.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
# License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
# coding: utf-8

"""
Okta Admin Management

Allows customers to easily access the Okta Management APIs

The version of the OpenAPI document: 5.1.0
Contact: devex-public@okta.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class IdPKeyCredential(BaseModel):
    """
    A [JSON Web Key](https://tools.ietf.org/html/rfc7517) for a signature or encryption credential for an IdP
    """  # noqa: E501

    created: Optional[datetime] = Field(
        default=None, description="Timestamp when the object was created"
    )
    e: Optional[StrictStr] = Field(
        default=None, description="The exponent value for the RSA public key"
    )
    expires_at: Optional[datetime] = Field(
        default=None, description="Timestamp when the object expires", alias="expiresAt"
    )
    kid: Optional[StrictStr] = Field(
        default=None, description="Unique identifier for the key"
    )
    kty: Optional[StrictStr] = Field(
        default=None,
        description="Identifies the cryptographic algorithm family used with the key",
    )
    last_updated: Optional[datetime] = Field(
        default=None,
        description="Timestamp when the object was last updated",
        alias="lastUpdated",
    )
    n: Optional[StrictStr] = Field(
        default=None, description="The modulus value for the RSA public key"
    )
    use: Optional[StrictStr] = Field(
        default=None, description="Intended use of the public key"
    )
    x5c: Optional[List[StrictStr]] = Field(
        default=None,
        description="Base64-encoded X.509 certificate chain with DER encoding",
    )
    x5t_s256: Optional[StrictStr] = Field(
        default=None,
        description="Base64url-encoded SHA-256 thumbprint of the DER encoding of an X.509 certificate",
        alias="x5t#S256",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "created",
        "e",
        "expiresAt",
        "kid",
        "kty",
        "lastUpdated",
        "n",
        "use",
        "x5c",
        "x5t#S256",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdPKeyCredential from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "created",
                "expires_at",
                "last_updated",
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdPKeyCredential from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "created": obj.get("created"),
                "e": obj.get("e"),
                "expiresAt": obj.get("expiresAt"),
                "kid": obj.get("kid"),
                "kty": obj.get("kty"),
                "lastUpdated": obj.get("lastUpdated"),
                "n": obj.get("n"),
                "use": obj.get("use"),
                "x5c": obj.get("x5c"),
                "x5t#S256": obj.get("x5t#S256"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
