# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API  # noqa: E501

    OpenAPI spec version: 2.9.2
    Contact: devex-public@okta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

import okta.models as models  # noqa
from okta.helpers import to_snake_case

class IdentityProviderApplicationUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {}
    swagger_types['embedded'] = 'dict(str, object)'
    swagger_types['links'] = 'dict(str, object)'
    swagger_types['created'] = 'str'
    swagger_types['external_id'] = 'str'
    swagger_types['id'] = 'str'
    swagger_types['last_updated'] = 'str'
    swagger_types['profile'] = 'dict(str, object)'

    attribute_map = {
        'embedded': '_embedded',
        'links': '_links',
        'created': 'created',
        'external_id': 'externalId',
        'id': 'id',
        'last_updated': 'lastUpdated',
        'profile': 'profile'
    }

    def __init__(self, config=None):
        if config is not None:
            config = {to_snake_case(key): value for key, value in config.items()}
        else:
            config = {}
        self.set_attributes(**config)

    @classmethod
    def from_kwargs(cls, **kwargs):
        return cls(config=kwargs)

    def set_attributes(self, embedded=None, links=None, created=None, external_id=None, id=None, last_updated=None, profile=None, **kwargs):  # noqa: E501
        """IdentityProviderApplicationUser - a model defined in Swagger"""  # noqa: E501
        self._embedded = None
        self._links = None
        self._created = None
        self._external_id = None
        self._id = None
        self._last_updated = None
        self._profile = None
        self.discriminator = None
        if embedded is not None:
            if hasattr(models, self.swagger_types['embedded']):
                nested_class = getattr(models, self.swagger_types['embedded'])
                if isinstance(embedded, nested_class):
                    self.embedded = embedded
                elif isinstance(embedded, dict):
                    self.embedded = nested_class.from_kwargs(**embedded)
                else:
                    self.embedded = embedded
            else:
                self.embedded = embedded
        if links is not None:
            if hasattr(models, self.swagger_types['links']):
                nested_class = getattr(models, self.swagger_types['links'])
                if isinstance(links, nested_class):
                    self.links = links
                elif isinstance(links, dict):
                    self.links = nested_class.from_kwargs(**links)
                else:
                    self.links = links
            else:
                self.links = links
        if created is not None:
            if hasattr(models, self.swagger_types['created']):
                nested_class = getattr(models, self.swagger_types['created'])
                if isinstance(created, nested_class):
                    self.created = created
                elif isinstance(created, dict):
                    self.created = nested_class.from_kwargs(**created)
                else:
                    self.created = created
            else:
                self.created = created
        if external_id is not None:
            if hasattr(models, self.swagger_types['external_id']):
                nested_class = getattr(models, self.swagger_types['external_id'])
                if isinstance(external_id, nested_class):
                    self.external_id = external_id
                elif isinstance(external_id, dict):
                    self.external_id = nested_class.from_kwargs(**external_id)
                else:
                    self.external_id = external_id
            else:
                self.external_id = external_id
        if id is not None:
            if hasattr(models, self.swagger_types['id']):
                nested_class = getattr(models, self.swagger_types['id'])
                if isinstance(id, nested_class):
                    self.id = id
                elif isinstance(id, dict):
                    self.id = nested_class.from_kwargs(**id)
                else:
                    self.id = id
            else:
                self.id = id
        if last_updated is not None:
            if hasattr(models, self.swagger_types['last_updated']):
                nested_class = getattr(models, self.swagger_types['last_updated'])
                if isinstance(last_updated, nested_class):
                    self.last_updated = last_updated
                elif isinstance(last_updated, dict):
                    self.last_updated = nested_class.from_kwargs(**last_updated)
                else:
                    self.last_updated = last_updated
            else:
                self.last_updated = last_updated
        if profile is not None:
            if hasattr(models, self.swagger_types['profile']):
                nested_class = getattr(models, self.swagger_types['profile'])
                if isinstance(profile, nested_class):
                    self.profile = profile
                elif isinstance(profile, dict):
                    self.profile = nested_class.from_kwargs(**profile)
                else:
                    self.profile = profile
            else:
                self.profile = profile

    @property
    def embedded(self):
        """Gets the embedded of this IdentityProviderApplicationUser.  # noqa: E501


        :return: The embedded of this IdentityProviderApplicationUser.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """Sets the embedded of this IdentityProviderApplicationUser.


        :param embedded: The embedded of this IdentityProviderApplicationUser.  # noqa: E501
        :type: dict(str, object)
        """

        self._embedded = embedded

    @property
    def links(self):
        """Gets the links of this IdentityProviderApplicationUser.  # noqa: E501


        :return: The links of this IdentityProviderApplicationUser.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this IdentityProviderApplicationUser.


        :param links: The links of this IdentityProviderApplicationUser.  # noqa: E501
        :type: dict(str, object)
        """

        self._links = links

    @property
    def created(self):
        """Gets the created of this IdentityProviderApplicationUser.  # noqa: E501


        :return: The created of this IdentityProviderApplicationUser.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this IdentityProviderApplicationUser.


        :param created: The created of this IdentityProviderApplicationUser.  # noqa: E501
        :type: str
        """

        self._created = created

    @property
    def external_id(self):
        """Gets the external_id of this IdentityProviderApplicationUser.  # noqa: E501


        :return: The external_id of this IdentityProviderApplicationUser.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this IdentityProviderApplicationUser.


        :param external_id: The external_id of this IdentityProviderApplicationUser.  # noqa: E501
        :type: str
        """

        self._external_id = external_id

    @property
    def id(self):
        """Gets the id of this IdentityProviderApplicationUser.  # noqa: E501


        :return: The id of this IdentityProviderApplicationUser.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this IdentityProviderApplicationUser.


        :param id: The id of this IdentityProviderApplicationUser.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def last_updated(self):
        """Gets the last_updated of this IdentityProviderApplicationUser.  # noqa: E501


        :return: The last_updated of this IdentityProviderApplicationUser.  # noqa: E501
        :rtype: str
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated):
        """Sets the last_updated of this IdentityProviderApplicationUser.


        :param last_updated: The last_updated of this IdentityProviderApplicationUser.  # noqa: E501
        :type: str
        """

        self._last_updated = last_updated

    @property
    def profile(self):
        """Gets the profile of this IdentityProviderApplicationUser.  # noqa: E501


        :return: The profile of this IdentityProviderApplicationUser.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._profile

    @profile.setter
    def profile(self, profile):
        """Sets the profile of this IdentityProviderApplicationUser.


        :param profile: The profile of this IdentityProviderApplicationUser.  # noqa: E501
        :type: dict(str, object)
        """

        self._profile = profile

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IdentityProviderApplicationUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdentityProviderApplicationUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
