# The Okta software accompanied by this notice is provided pursuant to the following terms:
# Copyright © 2025-Present, Okta, Inc.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
# License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
# coding: utf-8

"""
Okta Admin Management

Allows customers to easily access the Okta Management APIs

The version of the OpenAPI document: 5.1.0
Contact: devex-public@okta.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from okta.models.password_policy_rule_action import PasswordPolicyRuleAction
from okta.models.self_service_password_reset_action import (
    SelfServicePasswordResetAction,
)


class PasswordPolicyRuleActions(BaseModel):
    """
    PasswordPolicyRuleActions
    """  # noqa: E501

    password_change: Optional[PasswordPolicyRuleAction] = Field(
        default=None, alias="passwordChange"
    )
    self_service_password_reset: Optional[SelfServicePasswordResetAction] = Field(
        default=None, alias="selfServicePasswordReset"
    )
    self_service_unlock: Optional[PasswordPolicyRuleAction] = Field(
        default=None, alias="selfServiceUnlock"
    )
    __properties: ClassVar[List[str]] = [
        "passwordChange",
        "selfServicePasswordReset",
        "selfServiceUnlock",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PasswordPolicyRuleActions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of password_change
        if self.password_change:
            if not isinstance(self.password_change, dict):
                _dict["passwordChange"] = self.password_change.to_dict()
            else:
                _dict["passwordChange"] = self.password_change

        # override the default output from pydantic by calling `to_dict()` of self_service_password_reset
        if self.self_service_password_reset:
            if not isinstance(self.self_service_password_reset, dict):
                _dict["selfServicePasswordReset"] = (
                    self.self_service_password_reset.to_dict()
                )
            else:
                _dict["selfServicePasswordReset"] = self.self_service_password_reset

        # override the default output from pydantic by calling `to_dict()` of self_service_unlock
        if self.self_service_unlock:
            if not isinstance(self.self_service_unlock, dict):
                _dict["selfServiceUnlock"] = self.self_service_unlock.to_dict()
            else:
                _dict["selfServiceUnlock"] = self.self_service_unlock

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PasswordPolicyRuleActions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "passwordChange": (
                    PasswordPolicyRuleAction.from_dict(obj["passwordChange"])
                    if obj.get("passwordChange") is not None
                    else None
                ),
                "selfServicePasswordReset": (
                    SelfServicePasswordResetAction.from_dict(
                        obj["selfServicePasswordReset"]
                    )
                    if obj.get("selfServicePasswordReset") is not None
                    else None
                ),
                "selfServiceUnlock": (
                    PasswordPolicyRuleAction.from_dict(obj["selfServiceUnlock"])
                    if obj.get("selfServiceUnlock") is not None
                    else None
                ),
            }
        )
        return _obj
