# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API  # noqa: E501

    OpenAPI spec version: 2.10.0
    Contact: devex-public@okta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from okta.models.policy_rule_actions import PolicyRuleActions  # noqa: F401,E501

import okta.models as models  # noqa
from okta.helpers import to_snake_case

class ProfileEnrollmentPolicyRuleActions(PolicyRuleActions):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.

    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {}
    if hasattr(PolicyRuleActions, "swagger_types"):
        swagger_types.update(PolicyRuleActions.swagger_types)
    swagger_types['profile_enrollment'] = 'ProfileEnrollmentPolicyRuleAction'

    attribute_map = {
        'profile_enrollment': 'profileEnrollment'
    }
    if hasattr(PolicyRuleActions, "attribute_map"):
        attribute_map.update(PolicyRuleActions.attribute_map)

    def __init__(self, config=None):
        if config is not None:
            config = {to_snake_case(key): value for key, value in config.items()}
        else:
            config = {}
        self.set_attributes(**config)

    @classmethod
    def from_kwargs(cls, **kwargs):
        return cls(config=kwargs)

    def set_attributes(self, profile_enrollment=None, **kwargs):  # noqa: E501
        """ProfileEnrollmentPolicyRuleActions - a model defined in Swagger"""  # noqa: E501
        config = {}
        if kwargs is not None:
            config = {to_snake_case(key): value for key, value in kwargs.items()}
        super().set_attributes(**config)
        self._profile_enrollment = None
        self.discriminator = None
        if profile_enrollment is not None:
            if hasattr(models, self.swagger_types['profile_enrollment']):
                nested_class = getattr(models, self.swagger_types['profile_enrollment'])
                if isinstance(profile_enrollment, nested_class):
                    self.profile_enrollment = profile_enrollment
                elif isinstance(profile_enrollment, dict):
                    self.profile_enrollment = nested_class.from_kwargs(**profile_enrollment)
                else:
                    self.profile_enrollment = profile_enrollment
            else:
                self.profile_enrollment = profile_enrollment

    @property
    def profile_enrollment(self):
        """Gets the profile_enrollment of this ProfileEnrollmentPolicyRuleActions.  # noqa: E501


        :return: The profile_enrollment of this ProfileEnrollmentPolicyRuleActions.  # noqa: E501
        :rtype: ProfileEnrollmentPolicyRuleAction
        """
        return self._profile_enrollment

    @profile_enrollment.setter
    def profile_enrollment(self, profile_enrollment):
        """Sets the profile_enrollment of this ProfileEnrollmentPolicyRuleActions.


        :param profile_enrollment: The profile_enrollment of this ProfileEnrollmentPolicyRuleActions.  # noqa: E501
        :type: ProfileEnrollmentPolicyRuleAction
        """

        self._profile_enrollment = profile_enrollment

    def as_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.as_dict() if hasattr(x, "as_dict") else x,
                    value
                ))
            elif hasattr(value, "as_dict"):
                result[attr] = value.as_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].as_dict())
                    if hasattr(item[1], "as_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProfileEnrollmentPolicyRuleActions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.as_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProfileEnrollmentPolicyRuleActions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
