# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API  # noqa: E501

    OpenAPI spec version: 2.10.0
    Contact: devex-public@okta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

import okta.models as models  # noqa
from okta.helpers import to_snake_case

class SamlAttributeStatement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.

    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {}
    swagger_types['name'] = 'str'
    swagger_types['namespace'] = 'str'
    swagger_types['type'] = 'str'
    swagger_types['filter_type'] = 'str'
    swagger_types['filter_value'] = 'str'
    swagger_types['values'] = 'list[str]'

    attribute_map = {
        'name': 'name',
        'namespace': 'namespace',
        'type': 'type',
        'filter_type': 'filterType',
        'filter_value': 'filterValue',
        'values': 'values'
    }

    def __init__(self, config=None):
        if config is not None:
            config = {to_snake_case(key): value for key, value in config.items()}
        else:
            config = {}
        self.set_attributes(**config)

    @classmethod
    def from_kwargs(cls, **kwargs):
        return cls(config=kwargs)

    def set_attributes(self, name=None, namespace=None, type=None, filter_type=None, filter_value=None, values=None, **kwargs):  # noqa: E501
        """SamlAttributeStatement - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._namespace = None
        self._type = None
        self._filter_type = None
        self._filter_value = None
        self._values = None
        self.discriminator = None
        if name is not None:
            if hasattr(models, self.swagger_types['name']):
                nested_class = getattr(models, self.swagger_types['name'])
                if isinstance(name, nested_class):
                    self.name = name
                elif isinstance(name, dict):
                    self.name = nested_class.from_kwargs(**name)
                else:
                    self.name = name
            else:
                self.name = name
        if namespace is not None:
            if hasattr(models, self.swagger_types['namespace']):
                nested_class = getattr(models, self.swagger_types['namespace'])
                if isinstance(namespace, nested_class):
                    self.namespace = namespace
                elif isinstance(namespace, dict):
                    self.namespace = nested_class.from_kwargs(**namespace)
                else:
                    self.namespace = namespace
            else:
                self.namespace = namespace
        if type is not None:
            if hasattr(models, self.swagger_types['type']):
                nested_class = getattr(models, self.swagger_types['type'])
                if isinstance(type, nested_class):
                    self.type = type
                elif isinstance(type, dict):
                    self.type = nested_class.from_kwargs(**type)
                else:
                    self.type = type
            else:
                self.type = type
        if filter_type is not None:
            if hasattr(models, self.swagger_types['filter_type']):
                nested_class = getattr(models, self.swagger_types['filter_type'])
                if isinstance(filter_type, nested_class):
                    self.filter_type = filter_type
                elif isinstance(filter_type, dict):
                    self.filter_type = nested_class.from_kwargs(**filter_type)
                else:
                    self.filter_type = filter_type
            else:
                self.filter_type = filter_type
        if filter_value is not None:
            if hasattr(models, self.swagger_types['filter_value']):
                nested_class = getattr(models, self.swagger_types['filter_value'])
                if isinstance(filter_value, nested_class):
                    self.filter_value = filter_value
                elif isinstance(filter_value, dict):
                    self.filter_value = nested_class.from_kwargs(**filter_value)
                else:
                    self.filter_value = filter_value
            else:
                self.filter_value = filter_value
        if values is not None:
            if hasattr(models, self.swagger_types['values']):
                nested_class = getattr(models, self.swagger_types['values'])
                if isinstance(values, nested_class):
                    self.values = values
                elif isinstance(values, dict):
                    self.values = nested_class.from_kwargs(**values)
                else:
                    self.values = values
            else:
                self.values = values

    @property
    def name(self):
        """Gets the name of this SamlAttributeStatement.  # noqa: E501


        :return: The name of this SamlAttributeStatement.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SamlAttributeStatement.


        :param name: The name of this SamlAttributeStatement.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def namespace(self):
        """Gets the namespace of this SamlAttributeStatement.  # noqa: E501


        :return: The namespace of this SamlAttributeStatement.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this SamlAttributeStatement.


        :param namespace: The namespace of this SamlAttributeStatement.  # noqa: E501
        :type: str
        """

        self._namespace = namespace

    @property
    def type(self):
        """Gets the type of this SamlAttributeStatement.  # noqa: E501


        :return: The type of this SamlAttributeStatement.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SamlAttributeStatement.


        :param type: The type of this SamlAttributeStatement.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def filter_type(self):
        """Gets the filter_type of this SamlAttributeStatement.  # noqa: E501


        :return: The filter_type of this SamlAttributeStatement.  # noqa: E501
        :rtype: str
        """
        return self._filter_type

    @filter_type.setter
    def filter_type(self, filter_type):
        """Sets the filter_type of this SamlAttributeStatement.


        :param filter_type: The filter_type of this SamlAttributeStatement.  # noqa: E501
        :type: str
        """

        self._filter_type = filter_type

    @property
    def filter_value(self):
        """Gets the filter_value of this SamlAttributeStatement.  # noqa: E501


        :return: The filter_value of this SamlAttributeStatement.  # noqa: E501
        :rtype: str
        """
        return self._filter_value

    @filter_value.setter
    def filter_value(self, filter_value):
        """Sets the filter_value of this SamlAttributeStatement.


        :param filter_value: The filter_value of this SamlAttributeStatement.  # noqa: E501
        :type: str
        """

        self._filter_value = filter_value

    @property
    def values(self):
        """Gets the values of this SamlAttributeStatement.  # noqa: E501


        :return: The values of this SamlAttributeStatement.  # noqa: E501
        :rtype: list[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this SamlAttributeStatement.


        :param values: The values of this SamlAttributeStatement.  # noqa: E501
        :type: list[str]
        """

        self._values = values

    def as_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.as_dict() if hasattr(x, "as_dict") else x,
                    value
                ))
            elif hasattr(value, "as_dict"):
                result[attr] = value.as_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].as_dict())
                    if hasattr(item[1], "as_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SamlAttributeStatement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.as_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SamlAttributeStatement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
