# The Okta software accompanied by this notice is provided pursuant to the following terms:
# Copyright © 2025-Present, Okta, Inc.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
# License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
# coding: utf-8

"""
Okta Admin Management

Allows customers to easily access the Okta Management APIs

The version of the OpenAPI document: 5.1.0
Contact: devex-public@okta.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing_extensions import Annotated
from typing_extensions import Self

from okta.models.stream_configuration_aud import StreamConfigurationAud
from okta.models.stream_configuration_delivery import StreamConfigurationDelivery


class StreamConfiguration(BaseModel):
    """
    StreamConfiguration
    """  # noqa: E501

    aud: Optional[StreamConfigurationAud] = None
    delivery: StreamConfigurationDelivery
    events_delivered: Optional[List[StrictStr]] = Field(
        default=None,
        description="The events (mapped by the array of event type URIs) that the transmitter actually delivers to the SSF "
        "Stream.  A read-only parameter that is set by the transmitter. If this parameter is included in the "
        "request, the value must match the expected value from the transmitter.",
    )
    events_requested: Annotated[
        List[Annotated[str, Field(strict=True, max_length=256)]], Field(max_length=50)
    ] = Field(
        description="The events (mapped by the array of event type URIs) that the receiver wants to receive"
    )
    events_supported: Optional[List[StrictStr]] = Field(
        default=None,
        description="An array of event type URIs that the transmitter supports.  A read-only parameter that is set by the "
        "transmitter. If this parameter is included in the request, the value must match the expected value from "
        "the transmitter.",
    )
    format: Optional[StrictStr] = Field(
        default=None,
        description="The Subject Identifier format expected for any SET transmitted.",
    )
    iss: Optional[StrictStr] = Field(
        default=None,
        description="The issuer used in Security Event Tokens (SETs). This value is set as `iss` in the claim.  A read-only "
        "parameter that is set by the transmitter. If this parameter is included in the request, the value must "
        "match the expected value from the transmitter.",
    )
    min_verification_interval: Optional[StrictInt] = Field(
        default=None,
        description="The minimum amount of time, in seconds, between two verification requests.  A read-only parameter that "
        "is set by the transmitter. If this parameter is included in the request, the value must match the "
        "expected value from the transmitter.",
    )
    stream_id: Optional[StrictStr] = Field(
        default=None, description="The ID of the SSF Stream configuration"
    )
    __properties: ClassVar[List[str]] = [
        "aud",
        "delivery",
        "events_delivered",
        "events_requested",
        "events_supported",
        "format",
        "iss",
        "min_verification_interval",
        "stream_id",
    ]

    @field_validator("format")
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["iss_sub"]):
            raise ValueError("must be one of enum values ('iss_sub')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StreamConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of aud
        if self.aud:
            if not isinstance(self.aud, dict):
                _dict["aud"] = self.aud.to_dict()
            else:
                _dict["aud"] = self.aud

        # override the default output from pydantic by calling `to_dict()` of delivery
        if self.delivery:
            if not isinstance(self.delivery, dict):
                _dict["delivery"] = self.delivery.to_dict()
            else:
                _dict["delivery"] = self.delivery

        # set to None if min_verification_interval (nullable) is None
        # and model_fields_set contains the field
        if (
            self.min_verification_interval is None
            and "min_verification_interval" in self.model_fields_set
        ):
            _dict["min_verification_interval"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StreamConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "aud": (
                    StreamConfigurationAud.from_dict(obj["aud"])
                    if obj.get("aud") is not None
                    else None
                ),
                "delivery": (
                    StreamConfigurationDelivery.from_dict(obj["delivery"])
                    if obj.get("delivery") is not None
                    else None
                ),
                "events_delivered": obj.get("events_delivered"),
                "events_requested": obj.get("events_requested"),
                "events_supported": obj.get("events_supported"),
                "format": obj.get("format"),
                "iss": obj.get("iss"),
                "min_verification_interval": obj.get("min_verification_interval"),
                "stream_id": obj.get("stream_id"),
            }
        )
        return _obj
