# The Okta software accompanied by this notice is provided pursuant to the following terms:
# Copyright © 2025-Present, Okta, Inc.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
# License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
# coding: utf-8

"""
Okta Admin Management

Allows customers to easily access the Okta Management APIs

The version of the OpenAPI document: 5.1.0
Contact: devex-public@okta.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from importlib import import_module
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing import TYPE_CHECKING

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator

if TYPE_CHECKING:
    from okta.models.user_factor_push_transaction_rejected import (
        UserFactorPushTransactionRejected,
    )
    from okta.models.user_factor_push_transaction import UserFactorPushTransaction
    from okta.models.user_factor_push_transaction_timeout import (
        UserFactorPushTransactionTimeout,
    )
    from okta.models.user_factor_push_transaction_waiting_no_nmc import (
        UserFactorPushTransactionWaitingNoNMC,
    )
    from okta.models.user_factor_push_transaction_waiting_nmc import (
        UserFactorPushTransactionWaitingNMC,
    )


class UserFactorPushTransaction(BaseModel):  # noqa: F811
    """
    UserFactorPushTransaction
    """  # noqa: E501

    factor_result: Optional[StrictStr] = Field(
        default=None,
        description="Result of the verification transaction",
        alias="factorResult",
    )
    __properties: ClassVar[List[str]] = ["factorResult"]

    @field_validator("factor_result")
    def factor_result_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(
            [
                "WAITING (with number matching challenge)",
                "WAITING",
                "SUCCESS",
                "REJECTED",
                "TIMEOUT",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('WAITING (with number matching challenge)', 'WAITING', 'SUCCESS', 'REJECTED', "
                "'TIMEOUT')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = "factorResult"

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        "REJECTED": "UserFactorPushTransactionRejected",
        "SUCCESS": "UserFactorPushTransaction",
        "TIMEOUT": "UserFactorPushTransactionTimeout",
        "WAITING": "UserFactorPushTransactionWaitingNoNMC",
        "WAITING (with number matching challenge)": "UserFactorPushTransactionWaitingNMC",
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[
        Union[
            UserFactorPushTransactionRejected,
            UserFactorPushTransaction,
            UserFactorPushTransactionTimeout,
            UserFactorPushTransactionWaitingNoNMC,
            UserFactorPushTransactionWaitingNMC,
        ]
    ]:
        """Create an instance of UserFactorPushTransaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Optional[
        Union[
            UserFactorPushTransactionRejected,
            UserFactorPushTransaction,
            UserFactorPushTransactionTimeout,
            UserFactorPushTransactionWaitingNoNMC,
            UserFactorPushTransactionWaitingNMC,
        ]
    ]:
        """Create an instance of UserFactorPushTransaction from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type == "UserFactorPushTransactionRejected":
            return import_module(
                "okta.models.user_factor_push_transaction_rejected"
            ).UserFactorPushTransactionRejected.from_dict(obj)
        if object_type == "UserFactorPushTransaction":
            return import_module(
                "okta.models.user_factor_push_transaction"
            ).UserFactorPushTransaction.from_dict(obj)
        if object_type == "UserFactorPushTransactionTimeout":
            return import_module(
                "okta.models.user_factor_push_transaction_timeout"
            ).UserFactorPushTransactionTimeout.from_dict(obj)
        if object_type == "UserFactorPushTransactionWaitingNoNMC":
            return import_module(
                "okta.models.user_factor_push_transaction_waiting_no_nmc"
            ).UserFactorPushTransactionWaitingNoNMC.from_dict(obj)
        if object_type == "UserFactorPushTransactionWaitingNMC":
            return import_module(
                "okta.models.user_factor_push_transaction_waiting_nmc"
            ).UserFactorPushTransactionWaitingNMC.from_dict(obj)

        raise ValueError(
            "UserFactorPushTransaction failed to lookup discriminator value from "
            + json.dumps(obj)
            + ". Discriminator property name: "
            + cls.__discriminator_property_name
            + ", mapping: "
            + json.dumps(cls.__discriminator_value_class_map)
        )
