templateDir: ./templates
outputDir: ../sdk
packageName: okta
files:
  okta/okta_configuration.mustache:
    destinationFilename: okta/okta_configuration.py
    templateType: SupportingFiles
  okta/jwt.mustache:
    destinationFilename: okta/jwt.py
  okta/oauth.mustache:
    destinationFilename: okta/oauth.py
