# coding: utf-8

"""
    Okta Admin Management

    Allows customers to easily access the Okta Management APIs

    The version of the OpenAPI document: 5.1.0
    Contact: devex-public@okta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.role_assignment_api import RoleAssignmentApi


class TestRoleAssignmentApi(unittest.TestCase):
    """RoleAssignmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoleAssignmentApi()

    def tearDown(self) -> None:
        pass

    def test_assign_role_to_group(self) -> None:
        """Test case for assign_role_to_group

        Assign a Role to a Group
        """
        pass

    def test_assign_role_to_user(self) -> None:
        """Test case for assign_role_to_user

        Assign a Role to a User
        """
        pass

    def test_get_group_assigned_role(self) -> None:
        """Test case for get_group_assigned_role

        Retrieve a Role assigned to Group
        """
        pass

    def test_get_user_assigned_role(self) -> None:
        """Test case for get_user_assigned_role

        Retrieve a Role assigned to a User
        """
        pass

    def test_list_assigned_roles_for_user(self) -> None:
        """Test case for list_assigned_roles_for_user

        List all Roles assigned to a User
        """
        pass

    def test_list_group_assigned_roles(self) -> None:
        """Test case for list_group_assigned_roles

        List all Assigned Roles of Group
        """
        pass

    def test_list_users_with_role_assignments(self) -> None:
        """Test case for list_users_with_role_assignments

        List all Users with Role Assignments
        """
        pass

    def test_unassign_role_from_group(self) -> None:
        """Test case for unassign_role_from_group

        Unassign a Role from a Group
        """
        pass

    def test_unassign_role_from_user(self) -> None:
        """Test case for unassign_role_from_user

        Unassign a Role from a User
        """
        pass


if __name__ == '__main__':
    unittest.main()
