# coding: utf-8

"""
    Okta Admin Management

    Allows customers to easily access the Okta Management APIs

    The version of the OpenAPI document: 5.1.0
    Contact: devex-public@okta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.captcha_type import CAPTCHAType

class TestCAPTCHAType(unittest.TestCase):
    """CAPTCHAType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCAPTCHAType(self):
        """Test CAPTCHAType"""
        # inst = CAPTCHAType()

if __name__ == '__main__':
    unittest.main()
