# coding: utf-8

"""
    Okta Admin Management

    Allows customers to easily access the Okta Management APIs

    The version of the OpenAPI document: 5.1.0
    Contact: devex-public@okta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.brand import Brand

class TestBrand(unittest.TestCase):
    """Brand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Brand:
        """Test Brand
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Brand`
        """
        model = Brand()
        if include_optional:
            return Brand(
                agree_to_custom_privacy_policy = True,
                custom_privacy_policy_url = '',
                default_app = openapi_client.models.default_app.DefaultApp(
                    app_instance_id = '', 
                    app_link_name = '', 
                    classic_application_uri = '', ),
                email_domain_id = '',
                id = '',
                is_default = True,
                locale = '',
                name = '',
                remove_powered_by_okta = True
            )
        else:
            return Brand(
        )
        """

    def testBrand(self):
        """Test Brand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
