name: Other
description: Choose this option if your issue does not fit any of the other forms.
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for raising an issue!

        This form is a catch-all for issues that do not fit into one of the other categories. Please provide as much information, context, or reference material as possible.

        Before submission, we ask that you first [search existing issues](https://github.com/okta/okta-sdk-python/issues) and [pull requests](https://github.com/okta/okta-sdk-python/pulls) to see if someone else may have already reported your issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a brief description of what you're looking to report to the maintainers.
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Important Facts and References
      description: |
        Where possible, please supply links to documentation and/or other GitHub issues or pull requests that give additional context.
    validations:
      required: false
  - type: textarea
    id: customer_info
    attributes:
      label: Customer Information
      description: |
        Please provide your organization name, and whether you are a paid customer or using the free developer edition.
      value: |
        Organization Name: <your-org-name>
        Paid Customer: <yes/no>
  - type: dropdown
    id: will_contribute
    attributes:
      label: Would you like to implement a relevant change?
      description: |
        Indicate to the maintainers whether you plan to implement a change related to this. This helps prevent duplication of effort.

        If this would be your first contribution, refer to the [contributors guide](https://github.com/okta/okta-sdk-python/blob/master/.github/CONTRIBUTING.md) for tips on getting started.
      options:
        - "No"
        - "Yes"
      multiple: false
    validations:
      required: true