# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API  # noqa: E501

    OpenAPI spec version: 2.7.0
    Contact: devex-public@okta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.event_hook_api import EventHookApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEventHookApi(unittest.TestCase):
    """EventHookApi unit test stubs"""

    def setUp(self):
        self.api = EventHookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_event_hook(self):
        """Test case for activate_event_hook

        """
        pass

    def test_create_event_hook(self):
        """Test case for create_event_hook

        """
        pass

    def test_deactivate_event_hook(self):
        """Test case for deactivate_event_hook

        """
        pass

    def test_delete_event_hook(self):
        """Test case for delete_event_hook

        """
        pass

    def test_get_event_hook(self):
        """Test case for get_event_hook

        """
        pass

    def test_list_event_hooks(self):
        """Test case for list_event_hooks

        """
        pass

    def test_update_event_hook(self):
        """Test case for update_event_hook

        """
        pass

    def test_verify_event_hook(self):
        """Test case for verify_event_hook

        """
        pass


if __name__ == '__main__':
    unittest.main()
