# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API  # noqa: E501

    OpenAPI spec version: 2.7.0
    Contact: devex-public@okta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.u2f_user_factor import U2fUserFactor  # noqa: E501
from swagger_client.rest import ApiException


class TestU2fUserFactor(unittest.TestCase):
    """U2fUserFactor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testU2fUserFactor(self):
        """Test U2fUserFactor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.u2f_user_factor.U2fUserFactor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
