# The Okta software accompanied by this notice is provided pursuant to the following terms:
# Copyright © 2025-Present, Okta, Inc.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
# License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
# coding: utf-8

"""
Okta Admin Management

Allows customers to easily access the Okta Management APIs

The version of the OpenAPI document: 5.1.0
Contact: devex-public@okta.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import asyncio
import json
import logging
import time
from typing import Any, Dict, Optional, Tuple, TYPE_CHECKING

from okta.constants import MAX_DPOP_NONCE_RETRIES, MAX_DPOP_BACKOFF_DELAY

# Try to import DPoP - may fail if crypto libraries not installed
# This deferred import pattern is intentional for optional dependencies:
# - Allows SDK to work without DPoP dependencies if DPoP is not used
# - Provides clear error message when DPoP is enabled but dependencies missing
# - Avoids import-time failures for users who don't need DPoP functionality
_dpop_import_error_msg = None
DPoPProofGenerator = None
try:
    from okta.dpop import DPoPProofGenerator
except ImportError as e:
    _dpop_import_error_msg = str(e)

from okta.errors.dpop_errors import get_dpop_error_message, is_dpop_error  # noqa: E402
from okta.errors.okta_api_error import OktaAPIError  # noqa: E402
from okta.http_client import HTTPClient  # noqa: E402
from okta.jwt import JWT  # noqa: E402

if TYPE_CHECKING:
    from okta.dpop import DPoPProofGenerator as DPoPProofGeneratorType
else:
    DPoPProofGeneratorType = Any

logger = logging.getLogger("okta-sdk-python")


class OAuth:
    """
    This class contains the OAuth actions for the Okta Client.
    """

    OAUTH_ENDPOINT = "/oauth2/v1/token"

    def __init__(self, request_executor: Any, config: Dict[str, Any]) -> None:
        self._request_executor = request_executor
        self._config = config
        self._access_token: Optional[str] = None
        self._token_type: str = "Bearer"
        self._access_token_expiry_time: Optional[int] = None

        # Thread safety: Protect token state from concurrent access
        self._token_lock = asyncio.Lock()

        # Initialize DPoP if enabled
        self._dpop_enabled: bool = config["client"].get("dpopEnabled", False)
        self._dpop_generator: Optional[Any] = None

        if self._dpop_enabled:
            if DPoPProofGenerator is None:
                logger.error(
                    f"DPoP enabled but crypto libraries unavailable: {_dpop_import_error_msg}"
                )
                error = (
                    ImportError(_dpop_import_error_msg)
                    if _dpop_import_error_msg
                    else ImportError("DPoP import failed")
                )
                raise ValueError(
                    "DPoP requires 'pycryptodomex' and 'jwcrypto' libraries. "
                    "Install with: pip install pycryptodomex>=3.23.0 jwcrypto>=1.5.6"
                ) from error

            try:
                self._dpop_generator = DPoPProofGenerator(config["client"])
                logger.debug("DPoP authentication enabled")
            except Exception as e:
                logger.error(f"Failed to initialize DPoP generator: {e}")
                raise ValueError(f"DPoP initialization failed: {e}") from e

    def get_JWT(self) -> str:
        """
        Generates JWT using client configuration

        Returns:
            str: Generated JSON Web Token
        """
        org_url = self._config["client"]["orgUrl"]
        client_id = self._config["client"]["clientId"]
        private_key = self._config["client"]["privateKey"]
        # check if kid is provided in config - set if so
        kid = self._config["client"]["kid"] if "kid" in self._config["client"] else None

        return JWT.create_token(org_url, client_id, private_key, kid)

    @staticmethod
    def _parse_json_response(
        res_body: Optional[str], res_details: Optional[Any]
    ) -> Optional[Dict[str, Any]]:
        """
        Parse response body if JSON content type.

        Args:
            res_body: Response body string
            res_details: Response details object with content_type

        Returns:
            Parsed JSON dict or None if not JSON or parse error
        """
        if res_body and res_details and res_details.content_type == "application/json":
            try:
                parsed = json.loads(res_body)
                if not isinstance(parsed, dict):
                    logger.warning(
                        f"Expected dict response, got {type(parsed).__name__}. "
                        "This may indicate an unexpected API response format."
                    )
                    return None
                return parsed
            except (json.JSONDecodeError, ValueError, TypeError) as e:
                logger.error(f"JSON decode error: {e}")
                return None
        return None

    async def get_access_token(self) -> Tuple[Optional[str], Optional[Exception]]:
        """
        Retrieves or generates the OAuth access token for the Okta Client.

        BACKWARD COMPATIBILITY NOTE:
        ---------------------------
        This method returns a 2-tuple (token, error) for backward compatibility.
        For DPoP support, use get_oauth_token() instead, which returns a 3-tuple
        (token, token_type, error) where token_type is either "Bearer" or "DPoP".

        This wrapper exists to maintain compatibility with existing code that expects:
            token, error = await oauth.get_access_token()

        New code should use:
            token, token_type, error = await oauth.get_oauth_token()

        Returns:
            tuple: (access_token, error) - Legacy 2-tuple for backward compatibility
        """
        access_token, _, error = await self.get_oauth_token()
        return (access_token, error)

    async def get_oauth_token(self) -> Tuple[Optional[str], str, Optional[Exception]]:
        """
        Retrieves or generates the OAuth access token for the Okta Client.
        Supports both Bearer and DPoP token types.

        Returns:
            tuple: (access_token, token_type, error) - token_type will be "DPoP" if DPoP is enabled
        """
        # Acquire lock to prevent race conditions in token state management
        async with self._token_lock:
            # Double-check pattern: Check expiry again after acquiring lock
            current_time = int(time.time())
            if self._access_token and hasattr(self, "_access_token_expiry_time"):
                renewal_offset = (
                    self._config["client"]["oauthTokenRenewalOffset"] * 60
                )  # Convert minutes to seconds
                if current_time + renewal_offset >= self._access_token_expiry_time:
                    self.clear_access_token()

            # Return token with type if already generated (after lock check)
            if self._access_token:
                return (self._access_token, self._token_type, None)

            # Otherwise create new one
            # Get JWT and create parameters for new Oauth token
            jwt = self.get_JWT()
            parameters = {
                "grant_type": "client_credentials",
                "scope": " ".join(self._config["client"]["scopes"]),
                "client_assertion_type": "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
                "client_assertion": jwt,
            }

            org_url = self._config["client"]["orgUrl"]
            url = f"{org_url}{OAuth.OAUTH_ENDPOINT}"

            # Prepare headers
            headers = {
                "Accept": "application/json",
                "Content-Type": "application/x-www-form-urlencoded",
            }

            # Add DPoP header if enabled (first attempt without nonce)
            if self._dpop_enabled:
                dpop_proof = self._dpop_generator.generate_proof_jwt(
                    http_method="POST", http_url=f"{org_url}{OAuth.OAUTH_ENDPOINT}"
                )
                headers["DPoP"] = dpop_proof
                logger.debug("Added DPoP proof to token request (no nonce)")

            # Craft request
            oauth_req, err = await self._request_executor.create_request(
                "POST",
                url,
                form=parameters,
                headers=headers,  # Use the headers dict with DPoP proof
                oauth=True,
            )

            if err:
                return (None, "Bearer", err)

            # First attempt
            _, res_details, res_body, err = await self._request_executor.fire_request(
                oauth_req
            )

            # Parse response body once (avoid double-parsing)
            parsed_response = self._parse_json_response(res_body, res_details)

            # Handle DPoP-specific errors first (RFC 9449 Section 7)
            if (
                res_details
                and res_details.status == 400
                and isinstance(parsed_response, dict)
            ):
                error_code = parsed_response.get("error", "")

                # Check for DPoP-specific errors

                if is_dpop_error(error_code):
                    # Special handling for use_dpop_nonce - this is retryable with backoff
                    if error_code == "use_dpop_nonce":
                        # Extract nonce from response header
                        # Note: aiohttp returns CIMultiDictProxy (case-insensitive)
                        # RFC 9110 specifies HTTP headers are case-insensitive
                        dpop_nonce = res_details.headers.get("dpop-nonce")

                        if dpop_nonce and self._dpop_enabled:
                            # Retry with exponential backoff (max 2 retries)
                            for retry_attempt in range(MAX_DPOP_NONCE_RETRIES):
                                logger.debug(
                                    f"Received DPoP nonce challenge, retrying with nonce "
                                    f"(attempt {retry_attempt + 1}/{MAX_DPOP_NONCE_RETRIES})"
                                )

                                # Store nonce
                                self._dpop_generator.set_nonce(dpop_nonce)

                                # Exponential backoff with upper bound: 0.1s, 0.2s (capped at MAX_DPOP_BACKOFF_DELAY)
                                if retry_attempt > 0:
                                    backoff_delay = min(
                                        0.1 * (2 ** (retry_attempt - 1)),
                                        MAX_DPOP_BACKOFF_DELAY,
                                    )
                                    logger.debug(
                                        f"Backing off for {backoff_delay}s before retry"
                                    )
                                    await asyncio.sleep(backoff_delay)

                                # Generate new client assertion JWT
                                jwt = self.get_JWT()
                                parameters["client_assertion"] = jwt

                                # Generate new DPoP proof with nonce
                                dpop_proof = self._dpop_generator.generate_proof_jwt(
                                    http_method="POST",
                                    http_url=f"{org_url}{OAuth.OAUTH_ENDPOINT}",
                                    nonce=dpop_nonce,
                                )
                                headers["DPoP"] = dpop_proof
                                logger.debug("Retrying token request with nonce")

                                # Retry request
                                oauth_req, err = (
                                    await self._request_executor.create_request(
                                        "POST",
                                        url,
                                        form=parameters,  # Send as form data, not URL params
                                        headers=headers,
                                        oauth=True,
                                    )
                                )

                                if err:
                                    return (None, "Bearer", err)

                                _, res_details, res_body, err = (
                                    await self._request_executor.fire_request(oauth_req)
                                )

                                # Re-parse response body for retry attempt
                                parsed_response = self._parse_json_response(
                                    res_body, res_details
                                )

                                # Check if retry succeeded or if we got another nonce
                                if (
                                    res_details
                                    and res_details.status == 400
                                    and isinstance(parsed_response, dict)
                                    and parsed_response.get("error") == "use_dpop_nonce"
                                ):
                                    # Got another nonce - update and retry (if attempts remain)
                                    new_nonce = res_details.headers.get("dpop-nonce")
                                    if new_nonce and new_nonce != dpop_nonce:
                                        # Check if we have retries remaining before continuing
                                        if retry_attempt < MAX_DPOP_NONCE_RETRIES - 1:
                                            logger.debug(
                                                f"Server provided new nonce, retrying "
                                                f"(attempt {retry_attempt + 2}/{MAX_DPOP_NONCE_RETRIES})"
                                            )
                                            dpop_nonce = new_nonce
                                            continue  # Try again with new nonce
                                        else:
                                            # Max retries reached with server still changing nonce
                                            logger.error(
                                                "Server keeps changing nonce, max retries reached"
                                            )
                                            return (
                                                None,
                                                "Bearer",
                                                OktaAPIError(
                                                    "https://developer.okta.com/docs/api/",
                                                    res_details,
                                                    f"DPoP nonce challenge failed: server keeps providing new nonces after "
                                                    f"{MAX_DPOP_NONCE_RETRIES} retries. Server may be rotating nonces too "
                                                    f"frequently.",
                                                ),
                                            )
                                    elif retry_attempt >= MAX_DPOP_NONCE_RETRIES - 1:
                                        # Final attempt failed
                                        return (
                                            None,
                                            "Bearer",
                                            OktaAPIError(
                                                "https://developer.okta.com/docs/api/",
                                                res_details,
                                                f"DPoP nonce challenge failed after "
                                                f"{MAX_DPOP_NONCE_RETRIES} retries. "
                                                f"Server may be rejecting nonce or rotating too frequently.",
                                            ),
                                        )
                                else:
                                    # Retry succeeded (or different error) - break retry loop
                                    break

                            # Continue to normal error handling and token extraction below
                    else:
                        # Non-retryable DPoP error - provide helpful message
                        error_msg = get_dpop_error_message(error_code)
                        error_description = parsed_response.get("error_description", "")
                        full_error_msg = f"{error_msg}"
                        if error_description:
                            full_error_msg += f"\n\nServer error: {error_description}"

                        logger.error(f"DPoP Error ({error_code}): {error_msg}")

                        return (
                            None,
                            "Bearer",
                            OktaAPIError(
                                "https://developer.okta.com/docs/api/",
                                res_details,
                                full_error_msg,
                            ),
                        )

            # Handle non-DPoP errors or successful responses

            # Return HTTP Client error if raised
            if err:
                return (None, "Bearer", err)

            # Check parsed response for error message (avoid re-parsing)
            if parsed_response:
                # Already parsed - check for error manually to avoid calling check_response_for_error
                if "error" in parsed_response or "errorCode" in parsed_response:
                    error_msg = (
                        parsed_response.get("error_description")
                        or parsed_response.get("errorSummary")
                        or str(parsed_response)
                    )
                    return (None, "Bearer", OktaAPIError(url, res_details, error_msg))

                # Success case - parsed_response already contains the token data
            else:
                # Not parsed yet (edge case: non-JSON response) - let check_response_for_error handle it
                parsed_response, err = HTTPClient.check_response_for_error(
                    url, res_details, res_body
                )
                # Return specific error if found in response
                if err:
                    return (None, "Bearer", err)

            # Extract token and token type
            access_token = parsed_response["access_token"]
            token_type = parsed_response.get("token_type", "Bearer")
            expires_in = parsed_response.get("expires_in", 3600)

            # Store token and type
            self._access_token = access_token
            self._token_type = token_type
            self._access_token_expiry_time = int(time.time()) + expires_in

            # Extract and store nonce from successful response (if present)
            if self._dpop_enabled and "dpop-nonce" in res_details.headers:
                self._dpop_generator.set_nonce(res_details.headers["dpop-nonce"])
                logger.debug("Stored nonce from successful response")

            # Warn if DPoP was requested but server returned Bearer
            if self._dpop_enabled and token_type == "Bearer":
                logger.warning(
                    "DPoP was enabled but server returned Bearer token. "
                    "Ensure DPoP is enabled for this application in Okta admin console."
                )
            else:
                logger.info(f"Successfully obtained {token_type} access token")

            return (access_token, token_type, None)

    def clear_access_token(self) -> None:
        """
        Clear currently used OAuth access token, probably expired.
        Also clears token type.
        """
        self._access_token = None
        self._token_type = "Bearer"  # Reset to default
        # Note: Cache is managed by request_executor
        # Token and type are now stored as atomic tuple in single cache entry
        self._request_executor._default_headers.pop("Authorization", None)
        self._request_executor._cache.delete("OKTA_ACCESS_TOKEN")
        self._access_token_expiry_time = None

    def get_dpop_generator(self) -> Optional["DPoPProofGeneratorType"]:
        """Get DPoP generator instance."""
        return self._dpop_generator

    def is_dpop_enabled(self) -> bool:
        """Check if DPoP is enabled for this OAuth client."""
        return self._dpop_enabled
