# coding: utf-8

"""
    Okta Admin Management

    Allows customers to easily access the Okta Management APIs

    The version of the OpenAPI document: 5.1.0
    Contact: devex-public@okta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from openapi_client.models.application_visibility_hide import ApplicationVisibilityHide
from typing import Optional, Set
from typing_extensions import Self

class ApplicationVisibility(BaseModel):
    """
    ApplicationVisibility
    """ # noqa: E501
    app_links: Optional[Dict[str, StrictBool]] = Field(None, alias="appLinks")
    auto_launch: Optional[StrictBool] = Field(None, alias="autoLaunch")
    auto_submit_toolbar: Optional[StrictBool] = Field(None, alias="autoSubmitToolbar")
    hide: Optional[ApplicationVisibilityHide] = None
    __properties: ClassVar[List[str]] = ["appLinks", "autoLaunch", "autoSubmitToolbar", "hide"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplicationVisibility from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of hide
        if self.hide:
            _dict['hide'] = self.hide.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplicationVisibility from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "appLinks": obj.get("appLinks"),
            "autoLaunch": obj.get("autoLaunch"),
            "autoSubmitToolbar": obj.get("autoSubmitToolbar"),
            "hide": ApplicationVisibilityHide.from_dict(obj["hide"]) if obj.get("hide") is not None else None
        })
        return _obj


