# coding: utf-8

"""
    Okta Admin Management

    Allows customers to easily access the Okta Management APIs

    The version of the OpenAPI document: 5.1.0
    Contact: devex-public@okta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from openapi_client.models.links_self import LinksSelf
from typing import Optional, Set
from typing_extensions import Self

class JsonWebKey(BaseModel):
    """
    JsonWebKey
    """ # noqa: E501
    alg: Optional[StrictStr] = None
    created: Optional[datetime] = None
    e: Optional[StrictStr] = None
    expires_at: Optional[datetime] = Field(None, alias="expiresAt")
    key_ops: Optional[conlist(StrictStr)] = None
    kid: Optional[StrictStr] = None
    kty: Optional[StrictStr] = None
    last_updated: Optional[datetime] = Field(None, alias="lastUpdated")
    n: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    use: Optional[StrictStr] = None
    x5c: Optional[conlist(StrictStr)] = None
    x5t: Optional[StrictStr] = None
    x5t_s256: Optional[StrictStr] = Field(None, alias="x5t#S256")
    x5u: Optional[StrictStr] = None
    links: Optional[LinksSelf] = Field(None, alias="_links")
    __properties: ClassVar[List[str]] = ["alg", "created", "e", "expiresAt", "key_ops", "kid", "kty", "lastUpdated", "n", "status", "use", "x5c", "x5t", "x5t#S256", "x5u", "_links"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonWebKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['_links'] = self.links.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonWebKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alg": obj.get("alg"),
            "created": obj.get("created"),
            "e": obj.get("e"),
            "expiresAt": obj.get("expiresAt"),
            "key_ops": obj.get("key_ops"),
            "kid": obj.get("kid"),
            "kty": obj.get("kty"),
            "lastUpdated": obj.get("lastUpdated"),
            "n": obj.get("n"),
            "status": obj.get("status"),
            "use": obj.get("use"),
            "x5c": obj.get("x5c"),
            "x5t": obj.get("x5t"),
            "x5t#S256": obj.get("x5t#S256"),
            "x5u": obj.get("x5u"),
            "_links": LinksSelf.from_dict(obj["_links"]) if obj.get("_links") is not None else None
        })
        return _obj


