# coding: utf-8

"""
    Okta Admin Management

    Allows customers to easily access the Okta Management APIs

    The version of the OpenAPI document: 5.1.0
    Contact: devex-public@okta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from openapi_client.models.links_self import LinksSelf
from openapi_client.models.trusted_origin_scope import TrustedOriginScope
from typing import Optional, Set
from typing_extensions import Self

class TrustedOrigin(BaseModel):
    """
    TrustedOrigin
    """ # noqa: E501
    created: Optional[datetime] = None
    created_by: Optional[StrictStr] = Field(None, alias="createdBy")
    id: Optional[StrictStr] = None
    last_updated: Optional[datetime] = Field(None, alias="lastUpdated")
    last_updated_by: Optional[StrictStr] = Field(None, alias="lastUpdatedBy")
    name: Optional[StrictStr] = None
    origin: Optional[StrictStr] = None
    scopes: Optional[conlist(TrustedOriginScope)] = None
    status: Optional[StrictStr] = None
    links: Optional[LinksSelf] = Field(None, alias="_links")
    __properties: ClassVar[List[str]] = ["created", "createdBy", "id", "lastUpdated", "lastUpdatedBy", "name", "origin", "scopes", "status", "_links"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrustedOrigin from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created",
            "id",
            "last_updated",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in scopes (list)
        _items = []
        if self.scopes:
            for _item in self.scopes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['scopes'] = _items
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['_links'] = self.links.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrustedOrigin from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created": obj.get("created"),
            "createdBy": obj.get("createdBy"),
            "id": obj.get("id"),
            "lastUpdated": obj.get("lastUpdated"),
            "lastUpdatedBy": obj.get("lastUpdatedBy"),
            "name": obj.get("name"),
            "origin": obj.get("origin"),
            "scopes": [TrustedOriginScope.from_dict(_item) for _item in obj["scopes"]] if obj.get("scopes") is not None else None,
            "status": obj.get("status"),
            "_links": LinksSelf.from_dict(obj["_links"]) if obj.get("_links") is not None else None
        })
        return _obj


